title: Document Verifier
description: Identifies the type of a document
about:


  This is a document Classifier using Deep Learning built using the fast.ai library.


  The web app interface was inspired from the project by [Nidhin Pattaniyil](https://npatta01.github.io)
  and [Reshama Shaikh](https://reshamas.github.io).


  More info and the source code can he found below.


  - [Blog](https://reshamas.github.io/deploying-deep-learning-models-on-web-and-mobile/)    

  - [Web app](https://food-img-classifier.herokuapp.com)

  - [Video](https://www.youtube.com/watch?v=7d2qFLeYvRc)


  To try out this mobile app

    - [Expo](https://expo.io/@npatta01/food-app)

    - [Android](https://play.google.com/store/apps/details?id=com.rsnp.foodclassifier)

    - [iOS](https://itunes.apple.com/us/app/food-classifier/id1445356461?ls=1&mt=8)



code: https://github.com/npatta01/web-deep-learning-classifier

sampleImages:
  - name: original
    url: https://upload.wikimedia.org/wikipedia/commons/b/ba/Lasagne_-_stonesoup.jpg
  - name: photocopy
    url: https://upload.wikimedia.org/wikipedia/commons/6/60/Sushi_platter.jpg
  - name: screenshot
    url: https://upload.wikimedia.org/wikipedia/commons/5/5b/Waffles_with_Strawberries.jpg
  - name: photocopy of a screenshot
    url: https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Solanum_melongena_24_08_2012_%281%29.JPG/1280px-Solanum_melongena_24_08_2012_%281%29.JPG
  - name: table (not in training & not a document)
    url: https://image.shutterstock.com/image-photo/brown-light-wooden-round-dining-260nw-588358070.jpg 
